

# Operating system (build VM template)
os:
  - Visual Studio 2015


# scripts that are called at very beginning, before repo cloning
init:
  - echo init step
  - git config --global core.autocrlf input
  - cmake --version
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%

# clone directory
clone_folder: c:\projects\libwb
# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# branches to build
branches:
  # whitelist
  only:
    - master

platform:
  - x64
configuration: 
  - Release

environment:
  P: "c:/projects/libs"


install:
  # by default, all script lines are interpreted as batch

build:
  project: ALL_BUILD.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\libwb
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%

# after_build:
#   - echo after_build step


# on_finish always executes regardless of passed or failed builds
# on_finish:
#   - echo on_finish step
#   - ps: ls